/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateServerImport } from './routes/create-server'
import { Route as IndexImport } from './routes/index'
import { Route as ServersIndexImport } from './routes/servers/index'
import { Route as ServersServerIdImport } from './routes/servers/$serverId'

// Create/Update Routes

const CreateServerRoute = CreateServerImport.update({
  id: '/create-server',
  path: '/create-server',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ServersIndexRoute = ServersIndexImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRoute,
} as any)

const ServersServerIdRoute = ServersServerIdImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-server': {
      id: '/create-server'
      path: '/create-server'
      fullPath: '/create-server'
      preLoaderRoute: typeof CreateServerImport
      parentRoute: typeof rootRoute
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdImport
      parentRoute: typeof rootRoute
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-server': typeof CreateServerRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers': typeof ServersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-server': typeof CreateServerRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers': typeof ServersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-server': typeof CreateServerRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/': typeof ServersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-server' | '/servers/$serverId' | '/servers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-server' | '/servers/$serverId' | '/servers'
  id: '__root__' | '/' | '/create-server' | '/servers/$serverId' | '/servers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateServerRoute: typeof CreateServerRoute
  ServersServerIdRoute: typeof ServersServerIdRoute
  ServersIndexRoute: typeof ServersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateServerRoute: CreateServerRoute,
  ServersServerIdRoute: ServersServerIdRoute,
  ServersIndexRoute: ServersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-server",
        "/servers/$serverId",
        "/servers/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-server": {
      "filePath": "create-server.tsx"
    },
    "/servers/$serverId": {
      "filePath": "servers/$serverId.tsx"
    },
    "/servers/": {
      "filePath": "servers/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
